name: stronks
description: Fitness tracker

publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.13.0
  google_sign_in: ^5.0.0
  http: ^0.13.0
  path_provider: ^2.0.0
  provider: ^5.0.0
  sign_in_with_apple: ^3.0.0
  sqflite: ^2.0.0+3
  in_app_purchase: ^1.0.6
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.0
  crypto: ^3.0.1
  font_awesome_flutter: ^9.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
