name: stronks
description: Fitness tracker

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
    version: '>=0.9.8'
  flutter:
    sdk: flutter
  build: ^2.0.1
  built_collection: ^5.0.0
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.13.0
  google_sign_in: ^5.0.0
  http: ^0.13.0
  mockito: ^5.0.0
  path_provider: ^2.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.4
  sign_in_with_apple: ^3.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
